#!/bin/bash
#                                  MIT License
#                       Copyright 2026, Sébastien Kéroack
# ==============================================================================

# n8n configuration parameters
N8N_VERSION="2.3.5"
N8N_HOME="/home/job-search-pipeline/n8n" # Adjust path as needed (e.g., /d/home/job-search-pipeline/n8n for Windows)
PYTHON_VERSION="3.12"
JOBSPY_COMMIT_HASH="6e7ab6ff743f1317ebb909b4cb31d1e0a488167f" # Pinned commit hash for JobSpy submodule

# Google Cloud project and OAuth2 credentials
GOOGLE_PROJECT_NAME="job-search-pipeline test"
GOOGLE_PROJECT_ID="secret-heaven-XXXXXX-s4" # Auto-generated ID by Google Cloud
GOOGLE_EMAIL="XXXXXXXXXXXXXXXX@hotmail.com"
GOOGLE_APP_NAME="job-search-pipeline"
GOOGLE_APP_AUTH_NAME="job-search-pipeline-XXXXXXXXXXXXXXXX"
GOOGLE_APP_AUTH_CLIENT_ID="111111111111-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com" # Auto-generated by Google Cloud
GOOGLE_APP_AUTH_CLIENT_SECRET="XXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXX" # Auto-generated by Google Cloud

# OpenAI API credentials and model configuration
OPENAI_API_KEY="XX-XXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
OPENAI_API_MODEL="gpt-5-mini"

#| Model Name                | RAM Requirement | Context Length |
#|---------------------------|-----------------|----------------|
#| deepseek-r1:1.5b          | 3GB             | N/A            |
#| gpt-oss:20b               | 14GB            | 128K           |
#| gpt-oss:120b              | 65GB            | 128K           |
#| nemotron-3-nano:30b       | 24GB            | 1M             |
OLLAMA_MODEL="deepseek-r1:1.5b"
OLLAMA_VERSION="0.14.0"
OLLAMA_HOME="/home/job-search-pipeline/ollama" # Adjust path as needed (e.g., /d/home/job-search-pipeline/ollama for Windows)
OLLAMA_MAX_LOADED_MODELS=1
OLLAMA_CONTEXT_LENGTH=8192
OLLAMA_KEEP_ALIVE=1440m
OLLAMA_LOAD_TIMEOUT=60m
OLLAMA_NOHISTORY=1